### ISSUE TITLE
`Newest` tab is a duplicate of `Popular`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/plugin-manager#33]
I think this must've happened with 1.26.10 - 1.26.12 because I don't remember ever seeing this before today

<img width="653" alt="Screenshot 2024-01-15 010830" src="https://github.com/openplanet-nl/plugin-manager/assets/37951898/329d2e52-dc4e-4163-9922-e73e9e88789e">

**Comment by codecat** [comment]
Might be a result of a website change actually, I think @sylae made a change in the API somewhere.
