### ISSUE TITLE
Plugin Manager Crash

### ISSUE THREAD

**Issue by C0D33X** [openplanet-nl/plugin-manager#7]
The ingame plugin manager crash on version 1.22.1 

See the attached pastebin with log

https://pastebin.com/aSKqbgQh

**Comment by codecat** [comment]
Do you know how this happened? Did you not have internet?

**Comment by C0D33X** [comment]
Happen when i want to open the plugin manager.

I try to uninstall and reinstall OP, but nothing change. I have internet, i can play Trackmania on server...

**Comment by codecat** [comment]
Can you post your Settings.ini?

**Comment by codecat** [comment]
Also, go to Openplanet -> Settings -> Plugin Manager -> Advanced, and turn on "Verbose log". Now reload the plugin manager and post your log again.

**Comment by codecat** [comment]
Thanks! This will be fixed in the next Openplanet update. To manually solve it for now, add a forward slash to the end of the "Base URL" setting in the "Advanced" tab of the plugin manager's settings.
